//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_System.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("POS_System.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _10_Best_Printable_Blank_Restaurant_Menus_PDF_for_Free_at_Printablee {
            get {
                object obj = ResourceManager.GetObject("10 Best Printable Blank Restaurant Menus PDF for Free at Printablee", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _10_Best_Printable_Blank_Restaurant_Menus_PDF_for_Free_at_Printablee1 {
            get {
                object obj = ResourceManager.GetObject("10 Best Printable Blank Restaurant Menus PDF for Free at Printablee1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _9112855d_25d0_42f7_a0dc_7d43a7e596d5 {
            get {
                object obj = ResourceManager.GetObject("9112855d-25d0-42f7-a0dc-7d43a7e596d5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BBQ_Bacon_Cowboy_Hotdogs {
            get {
                object obj = ResourceManager.GetObject("BBQ Bacon Cowboy Hotdogs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Beef_Tenderloin_and_Balsamic_Steak_Sauce_Recipe___HelloFresh {
            get {
                object obj = ResourceManager.GetObject("Beef Tenderloin and Balsamic Steak Sauce Recipe _ HelloFresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cartoon_Restaurant_Chef_Recruitment_Design_Poster_Vector_Background_Wallpaper_Image_For_Free_Download___Pngtree {
            get {
                object obj = ResourceManager.GetObject("Cartoon Restaurant Chef Recruitment Design Poster Vector Background Wallpaper Ima" +
                        "ge For Free Download - Pngtree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cartoon_Restaurant_Chef_Recruitment_Design_Poster_Vector_Background_Wallpaper_Image_For_Free_Download___Pngtree1 {
            get {
                object obj = ResourceManager.GetObject("Cartoon Restaurant Chef Recruitment Design Poster Vector Background Wallpaper Ima" +
                        "ge For Free Download - Pngtree1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Download_premium_image_of_Rectangle_fast_food_frame_design_resource_by_katie_about_burger_background__burger_frame__beer__alcohol_beer_background_design__and_french_fries_2382354 {
            get {
                object obj = ResourceManager.GetObject("Download premium image of Rectangle fast food frame design resource by katie abou" +
                        "t burger background, burger frame, beer, alcohol beer background design, and fre" +
                        "nch fries 2382354", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Download_premium_image_of_Rectangle_fast_food_frame_design_resource_by_katie_about_burger_background__burger_frame__beer__alcohol_beer_background_design__and_french_fries_23823541 {
            get {
                object obj = ResourceManager.GetObject("Download premium image of Rectangle fast food frame design resource by katie abou" +
                        "t burger background, burger frame, beer, alcohol beer background design, and fre" +
                        "nch fries 23823541", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Download_premium_psd___image_of_Gold_frame_on_fresh_homemade_food_recipe_idea_by_kanate_about_cooking_frame__food_frame__cooking__recipe_frame__and_background_2451813 {
            get {
                object obj = ResourceManager.GetObject("Download premium psd _ image of Gold frame on fresh homemade food recipe idea by " +
                        "kanate about cooking frame, food frame, cooking, recipe frame, and background 24" +
                        "51813", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Google_Images {
            get {
                object obj = ResourceManager.GetObject("Google Images", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Home_Icon_Silhouette_free_icons_designed_by_Freepik {
            get {
                object obj = ResourceManager.GetObject("Home Icon Silhouette free icons designed by Freepik", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Home_Icon_Silhouette_free_icons_designed_by_Freepik1 {
            get {
                object obj = ResourceManager.GetObject("Home Icon Silhouette free icons designed by Freepik1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Home_Icon_Silhouette_free_icons_designed_by_Freepik2 {
            get {
                object obj = ResourceManager.GetObject("Home Icon Silhouette free icons designed by Freepik2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ícones_de_Sair_Para_Botao_App_para_download_gratuito {
            get {
                object obj = ResourceManager.GetObject("Ícones de Sair Para Botao App para download gratuito", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MEXICAN_CHORIZO___GARLIC_SHRIMP_BURGER {
            get {
                object obj = ResourceManager.GetObject("MEXICAN CHORIZO + GARLIC SHRIMP BURGER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
